### ISSUE TITLE
Get the OS / current machine UUID

### ISSUE THREAD

**Issue by danepowell** [drupol/phposinfo#3]
A lot of folks (myself included) use this package to assist with telemetry reporting. Having a unique machine identifier for each installation is critical for accurate telemetry.

Similar packages in other ecosystems (such as https://github.com/sebhildebrandt/systeminformation for Node) provide a function to get a machine identifier.

Would you be receptive to adding such a function?

We've been using the following in our applications, I think you could easily add it. Let me know if you want a PR.

```php
/**
   * Get a unique ID for the current running environment.
   *
   * Should conform to UUIDs generated by sebhildebrandt/systeminformation.
   *
   * @see https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js
   *
   * @return string|null
   *   The machine UUID.
   */
  public static function getMachineUuid() {
    switch (OsInfo::family()) {
      case FamilyName::LINUX:
        return shell_exec('( cat /var/lib/dbus/machine-id /etc/machine-id 2> /dev/null || hostname ) | head -n 1 || :');

      case FamilyName::DARWIN:
        $output = shell_exec('ioreg -rd1 -c IOPlatformExpertDevice | grep IOPlatformUUID');
        $parts = explode('=', str_replace('"', '', $output));
        return strtolower(trim($parts[1]));

      case FamilyName::WINDOWS:
        return shell_exec('%windir%\\System32\\reg query "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography" /v MachineGuid');

      default:
        return NULL;
    }
  }
```

**Comment by drupol** [comment]
Hi @danepowell,

I'll be happy to have contributions for sure.

I see in your code example that you're implementing that feature for Linux, Apple and Windows. How about adding the feature for other operating systems as well ? (BSD)

Thanks!

**Comment by danepowell** [comment]
Thanks, I can add BSD: https://github.com/drupol/phposinfo/pull/4
